# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49ea49d54615c439ffd26b1ed5fa96f4cfc99ac1ef1e20e6da4d363515f6b85f7638b1ba6dcbbebbbe61f8cfe725938492cf0780fa767f9a27e459f502b586c4

test:
  secret_key_base: 4d4f60170dc489d8e6f521dfebe85a2717cf8d97d5630dfcb8c15857c06e83b272ef3813ce303f38d2eb14e58b17c66794db6c9e1169a9e53c8a628d88fe8d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
